controller_manager:
  ros__parameters:
    update_rate: 50

    hardware_components_initial_state:
      inactive:
        - CatamaranSystem

    thruster_test_controller:
      type: forward_command_controller/ForwardCommandController

    body_force_controller:
      type: catamaran_controllers/BodyForceController

thruster_test_controller:
  ros__parameters:
    joints:
      - left_thruster_joint
      - right_thruster_joint
    interface_name: effort

body_force_controller:
  ros__parameters:
    input_topic: /body_force/command