controller_manager:
  ros__parameters:
    update_rate: 50

    thruster_test_controller:
      type: forward_command_controller/ForwardCommandController

thruster_test_controller:
  ros__parameters:
    joints:
      - left_thruster_joint
      - right_thruster_joint
    interface_name: effort